version: '3.8'

services:
    db:
        image: postgres:10.15-alpine
        restart: always
        ports:
            - 5555:5432
        environment:
            - POSTGRES_DB=test
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test